POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "firstName":"Dan",
  "lastName":"Cooper",
  "email":"12345qwe@gmail.com",
  "password":"coolpass",
  "birthday":"1990-06-05",
  "isMale":true
}